# Generated by Django 4.2.3 on 2023-08-01 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finalapplication', '0004_rename_sales_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_of_arrival',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sale',
            name='date_of_arrival',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
