# Generated by Django 4.2.3 on 2023-08-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapplication', '0006_rename_date_of_arrival_sale_date_of_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
